module.exports = {
  title: 'Java入門',
  author: 'Hidehiro Nagatani',
  language: 'ja',
  entry: [
    'cover.md',
    'chapter00.md',
    'chapter01.md',
    'chapter02.md',
    'chapter03.md',
    'chapter04.md',
    'chapter05.md',
    'chapter06.md',
    'chapter07.md',
    'chapter08.md',
    'chapter09.md',
    'chapter10.md',
    'chapter11.md',
    'chapter12.md',
    'chapter13.md',
    'chapter14.md',
    'chapter15.md',
    'chapter16.md',
    'chapter17.md',
    'chapter18.md',
    'glossary.md',
    'colophon.md',
  ],
  entryContext: './manuscripts',
  output: './output/techbook-java-primer.pdf',
  theme: '@vivliostyle/theme-techbook',
  workspaceDir: '.vivliostyle',
  toc: true,
  style: [
    '@vivliostyle/theme-techbook',
    './custom-styles.css'
  ],
};