apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd-app-staging

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=staging

images:
  - name: ghcr.io/myorg/cicd-cloud-native-app
    newTag: staging