apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: cicd-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard