# Native Image Dockerfile

# Stage 1: Native Image Build
FROM ghcr.io/graalvm/graalvm-ce:ol9-java17-22.3.3 AS builder

RUN gu install native-image

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN ./mvnw -Pnative native:compile

# Stage 2: Minimal Runtime
FROM gcr.io/distroless/base-debian11

WORKDIR /app

COPY --from=builder /app/target/cicd-cloud-native-app cicd-cloud-native-app

EXPOSE 8080

ENTRYPOINT ["/app/cicd-cloud-native-app"]